spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:onetime}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:otFkGpT9QX8VIXoh8bVGrC8RaCW+yBNlmoGLjJ0aAvE=}
      access-token-validity: 900
      refresh-token-validity: 10080
